import { ArrowUpRight } from 'lucide-react'
import { Link } from 'react-router'
import { Phone, OverviewScreen } from '../components/Phone'
import { Button, Eyebrow, Photo, PHOTOS, Reveal } from '../components/ui'

const products = [
  { n: '01', t: 'Income that adds up', d: 'See what came in, where it came from and what is changing.', c: 'bg-[#d9f5df]', to: '/money', bars: ['bg-signal', 'bg-sky', 'bg-amber'] },
  { n: '02', t: 'Invoices that move', d: 'Send, follow and get paid without leaving your flow.', c: 'bg-[#dcecff]', to: '/invoicing', bars: ['bg-sky', 'bg-coral', 'bg-signal'] },
  { n: '03', t: 'Tax without the shock', d: 'Keep reserve, deductions and documents moving quietly.', c: 'bg-[#fff0cd]', to: '/tax', bars: ['bg-amber', 'bg-signal', 'bg-ink'] },
  { n: '04', t: 'Goals with momentum', d: 'Turn the good months into progress you can see.', c: 'bg-[#eadfff]', to: '/goals', bars: ['bg-violet', 'bg-coral', 'bg-signal'] },
]

function MiniModule({ bars }: { bars: string[] }) {
  return <div className="relative mt-10 aspect-[1.42] overflow-hidden rounded-[14px] border border-ink/10 bg-paper p-4"><div className="flex items-center justify-between"><span className="h-2 w-16 rounded-full bg-ink" /><span className="h-5 w-5 rounded-full bg-signal" /></div><div className="mt-6 space-y-3">{bars.map((bar, i) => <div key={bar} className="flex items-center gap-3"><span className={`h-8 rounded-[5px] ${bar}`} style={{ width: `${86 - i * 19}%` }} /><span className="ml-auto h-2 w-6 rounded-full bg-stone" /></div>)}</div><div className="absolute -bottom-9 -right-9 h-28 w-28 rounded-full border-[18px] border-signal" /></div>
}

function Hero() {
  return <section className="bg-paper px-5 pb-16 pt-28 md:px-10 md:pb-24 md:pt-36"><div className="mx-auto grid max-w-[1280px] gap-12 lg:grid-cols-12 lg:items-end"><div className="lg:col-span-7"><Eyebrow>Finlancer for independent work</Eyebrow><h1 className="mt-6 max-w-[800px] text-[clamp(3.4rem,8vw,7.6rem)] font-semibold leading-[.84] tracking-[-.082em]">The money<br />side of <span className="text-signal-deep">freelancing.</span></h1><p className="mt-8 max-w-[490px] text-[17px] leading-relaxed text-ink-2">Everything between getting paid and knowing what to do next. Income, invoices, tax and goals in one mobile financial home.</p><div className="mt-9 flex flex-wrap gap-3"><Button to="/contact">Join the waitlist</Button><Button to="/product" variant="secondary">See how it works</Button></div></div><div className="relative mx-auto flex min-h-[430px] w-full justify-center overflow-hidden rounded-[26px] bg-[#d9f5df] pt-10 lg:col-span-5"><div className="absolute left-6 top-6 rounded-full bg-ink px-3 py-1.5 text-[11px] font-medium text-paper">Available today</div><div className="absolute right-[-65px] top-[-75px] h-48 w-48 rounded-full border-[26px] border-[#ffce31]" /><Phone className="relative z-10 !w-[250px] sm:!w-[275px]"><OverviewScreen /></Phone></div></div></section>
}

function ProductGrid() {
  return <section className="mx-auto max-w-[1280px] px-5 py-20 md:px-10 md:py-32"><div className="grid gap-8 lg:grid-cols-12"><div className="lg:col-span-5"><Eyebrow>One app. Four better habits.</Eyebrow><h2 className="mt-5 max-w-[500px] text-[clamp(2.5rem,5vw,4.8rem)] font-semibold leading-[.92] tracking-[-.065em]">Built around how your money actually moves.</h2></div><p className="self-end text-[16px] leading-relaxed text-ink-2 lg:col-span-4 lg:col-start-8">Freelance money is connected. A paid invoice changes your available balance, your tax reserve and what you can move towards a goal.</p></div><div className="mt-14 grid gap-4 sm:grid-cols-2">{products.map((p, i) => <Reveal key={p.t} delay={i * 70}><Link to={p.to} className={`product-tile group block min-h-[370px] ${p.c} p-6 md:p-8`}><div className="flex items-start justify-between"><span className="label text-ink/55">{p.n}</span><ArrowUpRight size={18} className="transition-transform duration-300 group-hover:-translate-y-1 group-hover:translate-x-1" /></div><h3 className="mt-9 max-w-[310px] text-[clamp(2rem,3.5vw,3.4rem)] font-semibold leading-[.9] tracking-[-.055em]">{p.t}</h3><p className="mt-4 max-w-[330px] text-[15px] leading-relaxed text-ink-2">{p.d}</p><MiniModule bars={p.bars} /></Link></Reveal>)}</div></section>
}

function WorkScene() {
  return <section className="mx-auto max-w-[1280px] px-5 pb-20 md:px-10 md:pb-32"><div className="grid gap-8 lg:grid-cols-12 lg:items-end"><div className="lg:col-span-6"><Eyebrow>For the work between the work</Eyebrow><h2 className="mt-5 max-w-[620px] text-[clamp(2.5rem,5vw,4.8rem)] font-semibold leading-[.92] tracking-[-.065em]">A clearer money picture, wherever the day takes you.</h2></div><p className="text-[16px] leading-relaxed text-ink-2 lg:col-span-4 lg:col-start-9">On a client call, at your desk or between projects, Finlancer gives your next decision a little more context.</p></div><div className="relative mt-12 h-[440px] overflow-hidden rounded-[24px] bg-ink md:h-[580px]"><Photo id={PHOTOS.studio} alt="A creative professional working in a bright studio" className="h-full w-full" w={1600} /><div className="absolute inset-0 bg-ink/15" /><div className="absolute left-4 top-5 rounded-[14px] bg-paper px-4 py-3 shadow-[0_14px_28px_-16px_rgba(0,0,0,.55)] md:left-8 md:top-8"><p className="label text-mute">Invoice paid</p><p className="mt-1 text-[18px] font-semibold tnum">+$2,400</p><p className="mt-0.5 text-[11px] text-signal-deep">Acme Studio</p></div><div className="absolute bottom-5 right-4 max-w-[230px] rounded-[14px] bg-paper px-4 py-3 shadow-[0_14px_28px_-16px_rgba(0,0,0,.55)] md:bottom-8 md:right-8"><p className="label text-mute">Goal moved</p><p className="mt-1 text-[17px] font-semibold">Studio Upgrade</p><p className="mt-1 text-[12px] text-signal-deep">+$240 from this payment</p></div></div></section>
}

function EditorialBreak() {
  return <section className="bg-ink px-5 py-20 text-paper md:px-10 md:py-32"><div className="mx-auto max-w-[1280px]"><Eyebrow className="text-signal">Independent work is not a salary</Eyebrow><p className="mt-8 max-w-[1080px] text-[clamp(3.1rem,8vw,7.6rem)] font-semibold leading-[.84] tracking-[-.078em]">Some months are full. Some are quiet. <span className="text-[#ffce31]">Your money needs a system that understands both.</span></p><div className="mt-16 grid gap-6 border-t border-white/15 pt-6 md:grid-cols-3"><p className="text-[14px] leading-relaxed text-paper/65">Income changes. Clients pay differently. Expenses arrive at inconvenient moments.</p><p className="text-[14px] leading-relaxed text-paper/65">Finlancer keeps the connected pieces visible, so the next decision is less of a guess.</p><Link to="/product" className="inline-flex items-center gap-2 self-start text-[14px] font-medium text-signal">Explore the product <ArrowUpRight size={16} /></Link></div></div></section>
}

function Flow() {
  const steps = [['Invoice paid', '+$4,200', 'bg-[#dcecff]'], ['Tax reserve', '$1,050', 'bg-[#fff0cd]'], ['Goal moved', '+$315', 'bg-[#eadfff]'], ['Available now', '$2,835', 'bg-[#d9f5df]']]
  return <section className="bg-paper-2 px-5 py-20 md:px-10 md:py-32"><div className="mx-auto max-w-[1280px]"><div className="grid gap-8 lg:grid-cols-12"><div className="lg:col-span-5"><Eyebrow>A payment changes everything</Eyebrow><h2 className="mt-5 max-w-[560px] text-[clamp(2.5rem,5vw,4.8rem)] font-semibold leading-[.92] tracking-[-.065em]">One good payment can do more than sit in your account.</h2></div></div><div className="mt-14 grid gap-3 md:grid-cols-4">{steps.map(([t, n, c], i) => <Reveal key={t} delay={i * 80}><div className={`rounded-[18px] ${c} p-5 md:min-h-[210px] md:p-6`}><span className="label text-ink/55">0{i + 1}</span><p className="mt-10 text-[21px] font-semibold leading-tight tracking-[-.035em]">{t}</p><p className="mt-2 text-[30px] font-semibold tracking-[-.05em] tnum">{n}</p></div></Reveal>)}</div></div></section>
}

function FinalCTA() {
  return <section className="bg-ink px-5 py-20 text-paper md:px-10 md:py-32"><div className="mx-auto flex max-w-[1280px] flex-col justify-between gap-10 md:flex-row md:items-end"><div><Eyebrow className="text-signal">Built for what is next</Eyebrow><h2 className="mt-5 max-w-[760px] text-[clamp(3.2rem,7vw,7rem)] font-semibold leading-[.84] tracking-[-.08em]">Make the next<br /><span className="text-[#ffce31]">good month count.</span></h2></div><Button to="/contact" className="shrink-0" variant="primary">Get started with Finlancer</Button></div></section>
}

export default function Home() { return <><Hero /><ProductGrid /><WorkScene /><EditorialBreak /><Flow /><FinalCTA /></> }
